baseURL = 'https://www.yuanhao.site'
languageCode = 'zh-CN'
title = '多头注意力'
theme = "PaperMod"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "archive"
weight = 10

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[socialIcons]]
name = "x"
url = "https://twitter.com/"

[[socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com"

[[socialIcons]]
name = "github"
url = "https://github.com/thuwyh"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
subtitle = "AI算命 朋克养生"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
comments = true
Description = "Cool staff about NLP, AI and beyond. 关于 NLP、人工智能的酷东西。"
author = "Yuanhao"

  [params.assets]
  favicon = "/assets/favicon.ico"
  favicon16x16 = "/assets/favicon.ico"
  favicon32x32 = "/assets/favicon.ico"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "欢迎关注同名公众号【多头注意力】"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://x.com/thuwyh"

  [[params.socialIcons]]
  name = "kaggle"
  url = "https://www.kaggle.com/wuyhbb"

  [[params.socialIcons]]
  name = "zhihu"
  url = "https://www.zhihu.com/people/fjshwyh"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/thuwyh"

  [[params.socialIcons]]
  name = "googlescholar"
  url = "https://scholar.google.com/citations?user=bzCZ4p0AAAAJ&hl=en"

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  limit = 10
  keys = [ "title", "permalink", "summary", "content" ]

[services]
  [services.disqus]
    shortname = 'multihead-attention'
  [services.googleAnalytics]
    id = 'G-NWW8ZQMQ6Y'